
package businesslayer.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgriturServiceImplService", targetNamespace = "http://ws.businesslayer/", wsdlLocation = "https://businesslayer.herokuapp.com/agritur?wsdl")
public class AgriturServiceImplService
    extends Service
{

    private final static URL AGRITURSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGRITURSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName AGRITURSERVICEIMPLSERVICE_QNAME = new QName("http://ws.businesslayer/", "AgriturServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://businesslayer.herokuapp.com/agritur?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGRITURSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        AGRITURSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AgriturServiceImplService() {
        super(__getWsdlLocation(), AGRITURSERVICEIMPLSERVICE_QNAME);
    }

    public AgriturServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGRITURSERVICEIMPLSERVICE_QNAME, features);
    }

    public AgriturServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, AGRITURSERVICEIMPLSERVICE_QNAME);
    }

    public AgriturServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGRITURSERVICEIMPLSERVICE_QNAME, features);
    }

    public AgriturServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgriturServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgriturService
     */
    @WebEndpoint(name = "AgriturServiceImplPort")
    public AgriturService getAgriturServiceImplPort() {
        return super.getPort(new QName("http://ws.businesslayer/", "AgriturServiceImplPort"), AgriturService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgriturService
     */
    @WebEndpoint(name = "AgriturServiceImplPort")
    public AgriturService getAgriturServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.businesslayer/", "AgriturServiceImplPort"), AgriturService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGRITURSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw AGRITURSERVICEIMPLSERVICE_EXCEPTION;
        }
        return AGRITURSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
